//! Reading `steam-games.tsv`: the half of the snapshot that was never built.
//!
//! The file is **compiled in**, not opened. It is the program's own reference data, it is
//! regenerated by running a tool rather than by anything at runtime, and a lookup that costs a
//! file open and a 28 MB parse the first time is a lookup callers avoid making. Measured, the
//! price is +1.5 s on a release build and +26.8 MB of binary — see [`SNAPSHOT`].
//!
//! Nothing here allocates a copy of a row. Every string an [`Entry`] hands back borrows from the
//! compiled-in text, so a lookup costs a search and nothing else.
//!
//! # Two lookups, two binary searches
//!
//! By app-id the file is **sorted**, so [`by_id`] binary-searches the text itself. By title it is
//! not, so the first [`by_name`] of the process sorts one pointer per row by folded title —
//! `BY_TITLE` — and every title lookup after it is a binary search too. That first call costs
//! what one scan of the file did; nothing else does.
//!
//! Measured over this snapshot, in release:
//!
//! | lookup | cost |
//! |---|---|
//! | [`by_id`], one app | 4.7 µs |
//! | [`by_ids`], 50 apps | 0.34 ms |
//! | [`by_name`], the first in a process (builds the index) | 225 ms |
//! | [`by_name`], each after that | 29 µs |
//! | [`by_names`], 50 titles | 1.3 ms |
//!
//! The index replaced a scan of the whole file per title — 125 ms each in release, 960 ms in a
//! debug build — which [`crate::inventory::steam::app_id_of`] made once per game a store
//! published no usable id for (every Humble game, every game inside a pack), from more than one
//! caller per render.

use super::codec::{Compat, Languages, from_base36, from_base36_wide};
use crate::inventory::steam::{Os, Rating, comparable, without_edition};

/// The row's columns, in order: the single list the writer and the reader share.
///
/// `steam_catalogue` builds its header from this and fills a `?` row to this width; the index
/// constants below are checked against it by a test, so adding a column cannot leave the writer
/// and the reader disagreeing about which field is which.
pub const COLUMNS: &[&str] = &[
    "app_id",
    "type",
    "band",
    "approval",
    "reviews",
    "released",
    "os",
    "vr",
    "early",
    "deck",
    "compat",
    "lang_ui",
    "lang_audio",
    "lang_subs",
    "tagids(base36)",
    "incl(base36)",
    "feats(base36)",
    "devs",
    "pubs",
    "name",
];

const APP_ID: usize = 0;
const KIND: usize = 1;
const BAND: usize = 2;
const APPROVAL: usize = 3;
const REVIEWS: usize = 4;
const RELEASED: usize = 5;
const OS: usize = 6;
const VR: usize = 7;
const EARLY: usize = 8;
const DECK: usize = 9;
const COMPAT: usize = 10;
const LANG_UI: usize = 11;
const TAGIDS: usize = 14;
const INCL: usize = 15;
const FEATS: usize = 16;
const DEVS: usize = 17;
const PUBS: usize = 18;
const NAME: usize = 19;

/// A cell the file knows nothing about — in ANY column but the app-id, and meaning nothing else.
///
/// A row of nothing else is an app whose id is all the file has; that the store refuses to
/// describe it is recorded in `steam-delisted-games.tsv` (see [`super::delisted`]), not in its
/// cells. A value the format could not hold is written `?` too, and `steam-issues.tsv` says why.
pub const UNKNOWN: &str = "?";

/// `released` for a game not out yet, with no date announced.
pub const UNANNOUNCED: &str = "TBA";

/// `released` for a game that is out and has no published date.
pub const UNDATED: &str = "X";

/// The mark before a `released` date a game is planned for rather than out on: `~2026-11-15`.
pub const PLANNED: char = '~';

/// When a game came out, as far as the file knows — the `released` column.
///
/// Out or not out, crossed with dated or undated. A cell saying [`UNKNOWN`] is none of these but
/// the file not knowing, which is why [`Details::released`] is an `Option` of this. The file's
/// spelling of each is here and nowhere else, so the sweep writes through [`Release::cell`] and
/// the reader reads through [`Release::from_cell`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Release<'a> {
    /// Out, on this day: `YYYY-MM-DD`.
    Out(&'a str),
    /// Not out yet; the store plans it for this day. Written with [`PLANNED`] before it.
    Planned(&'a str),
    /// Not out yet, and no date announced. Written [`UNANNOUNCED`].
    Unannounced,
    /// Out, and the store publishes no date for it. Written [`UNDATED`].
    Undated,
}

impl<'a> Release<'a> {
    /// The cell, as the file spells it.
    #[must_use]
    pub fn cell(self) -> String {
        match self {
            Self::Out(date) => date.to_owned(),
            Self::Planned(date) => format!("{PLANNED}{date}"),
            Self::Unannounced => UNANNOUNCED.to_owned(),
            Self::Undated => UNDATED.to_owned(),
        }
    }

    /// A cell read back: `Ok(None)` for [`UNKNOWN`].
    ///
    /// # Errors
    ///
    /// A cell that is none of the five shapes, or whose date is not a whole `YYYY-MM-DD`.
    pub fn from_cell(cell: &'a str) -> Result<Option<Self>, String> {
        let whole = |date: &str| date.len() == 10 && crate::steam::printed_date(date).is_some();
        match cell {
            UNKNOWN => Ok(None),
            UNANNOUNCED => Ok(Some(Self::Unannounced)),
            UNDATED => Ok(Some(Self::Undated)),
            _ => match cell.strip_prefix(PLANNED) {
                Some(date) if whole(date) => Ok(Some(Self::Planned(date))),
                None if whole(cell) => Ok(Some(Self::Out(cell))),
                _ => Err(format!(
                    "{cell:?} is not a date, {PLANNED}date, {UNANNOUNCED}, {UNDATED} or {UNKNOWN}"
                )),
            },
        }
    }

    /// Whether the store says the game is not out yet.
    #[must_use]
    pub const fn coming_soon(self) -> bool {
        matches!(self, Self::Planned(_) | Self::Unannounced)
    }

    /// The day it came out, or is planned for.
    #[must_use]
    pub const fn date(self) -> Option<&'a str> {
        match self {
            Self::Out(date) | Self::Planned(date) => Some(date),
            Self::Unannounced | Self::Undated => None,
        }
    }
}

/// Steam's catalogue, as `steam_catalogue` last wrote it.
///
/// **Compiled in deliberately, and it is not free.** Measured on this file at 28 MB: a release
/// build costs 1.5 s more and the binary grows by 26.8 MB. What that buys is a lookup with no
/// file to find, no I/O to fail and no parse to amortise — and a binary that still answers when
/// the working directory is not the repository.
pub const SNAPSHOT: &str = include_str!("../../../data/steam/steam-games.tsv");

/// One game, as the snapshot records it.
///
/// The app-id is always present. Every other cell may be unknown — [`UNKNOWN`] in the file,
/// `None` here — and one row can know some cells and not others: the file aggregates what each
/// source could say, so a partly known row is a normal row, not a damaged one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    /// Valve's app-id, the only field that is never unknown.
    pub app_id: u32,
    /// The store's title, or `""` when there is none to give.
    ///
    /// Empty covers two cases a caller matching titles has no use in telling apart: a title the
    /// store publishes as blank, and one the file does not know.
    pub name: &'static str,
    /// `None` when the file knows nothing about the app but its id.
    pub details: Option<Details>,
}

/// Everything the file knows about a game; each field `None` where its cell is unknown.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Details {
    /// Valve's product kind: 0 game, 11 music.
    pub kind: Option<u32>,
    /// Steam's own verdict. [`Rating::TooFewReviews`] is band 0, which is Steam declining to give
    /// one rather than a bad score.
    pub band: Option<Rating>,
    /// Percent of reviews that are positive — the "% Positive" a store page prints.
    pub approval: Option<u32>,
    /// How many reviews that percentage is over.
    pub reviews: Option<u32>,
    /// Out or not, and when.
    pub released: Option<Release<'static>>,
    /// Which systems the store lists; all three `false` is a store that lists none.
    pub os: Option<Os>,
    /// The store names at least one headset.
    pub vr: Option<bool>,
    /// Marked Early Access.
    pub early_access: Option<bool>,
    /// Steam Deck: 0 unknown to Valve, 1 unsupported, 2 playable, 3 verified.
    pub deck: Option<u32>,
    /// The three verdicts beside the Deck one.
    pub compat: Option<Compat>,
    /// Which languages the store lists, dubs and subtitles. All three masks zero is a store that
    /// lists none, which is not the same as not knowing.
    pub languages: Option<Languages>,
    tagids: Option<&'static str>,
    included: Option<&'static str>,
    feats: Option<&'static str>,
    developers: Option<&'static str>,
    publishers: Option<&'static str>,
}

impl Details {
    /// Valve's tag ids, strongest first — the order is the store's own, descending by vote weight.
    /// `None` when unknown; an empty list is a store that lists no tags.
    ///
    /// Resolve a name with [`super::tags::name`].
    pub fn tag_ids(&self) -> Option<impl Iterator<Item = u32> + use<>> {
        self.tagids.map(ids)
    }

    /// Other apps Steam ties to this one through its store item. Not a parent pointer and not
    /// reliably mutual — see the file's own header.
    pub fn included_apps(&self) -> Option<impl Iterator<Item = u32> + use<>> {
        self.included.map(ids)
    }

    /// Store feature ids, ascending. Resolve one with [`super::categories::of`].
    pub fn feature_ids(&self) -> Option<impl Iterator<Item = u32> + use<>> {
        self.feats.map(ids)
    }

    /// Studio names; semicolon-separated in the file, because a studio name contains commas.
    /// `None` when unknown — an empty list is a store that lists none.
    pub fn developers(&self) -> Option<impl Iterator<Item = &'static str> + use<>> {
        self.developers.map(named)
    }

    /// Publisher names, same shape as [`Details::developers`].
    pub fn publishers(&self) -> Option<impl Iterator<Item = &'static str> + use<>> {
        self.publishers.map(named)
    }
}

fn ids(column: &'static str) -> impl Iterator<Item = u32> + use<> {
    column
        .split(',')
        .filter(|token| !token.is_empty())
        .filter_map(|token| from_base36(token).ok())
}

/// A `;`-separated name list, empty-safe: an absent column yields nothing rather than one `""`.
fn named(column: &'static str) -> impl Iterator<Item = &'static str> + use<> {
    column.split(';').filter(|part| !part.is_empty())
}

/// Why a name did not resolve to one game.
///
/// Both arms are failures on purpose. A name matching nothing and a name matching six are
/// different problems for the caller — the first wants a different spelling, the second wants an
/// app-id — and collapsing them into `None` would hide which.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NotOne {
    /// Nothing in the snapshot has this title, loosely compared.
    Nothing,
    /// Several do. Their app-ids, ascending, so the caller can pick one and use [`by_id`].
    Several(Vec<u32>),
}

impl std::fmt::Display for NotOne {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Nothing => write!(f, "no game in the snapshot has that title"),
            Self::Several(ids) => {
                write!(f, "{} games share that title: ", ids.len())?;
                for (at, id) in ids.iter().enumerate() {
                    if at > 0 {
                        write!(f, ", ")?;
                    }
                    write!(f, "{id}")?;
                }
                Ok(())
            }
        }
    }
}

impl std::error::Error for NotOne {}

/// Where the data begins: the byte after the commented header, found once.
///
/// The header is a contiguous run of `#` lines, so this is a prefix scan and not a filter. It
/// matters because [`by_id`] binary-searches byte offsets, and a probe landing in the header must
/// not be mistaken for a row that sorts before every app-id.
static DATA_START: std::sync::LazyLock<usize> = std::sync::LazyLock::new(|| {
    let mut at = 0;
    while SNAPSHOT[at..].starts_with('#') {
        match SNAPSHOT[at..].find('\n') {
            Some(newline) => at += newline + 1,
            None => return SNAPSHOT.len(),
        }
    }
    at
});

/// One game by its Valve app-id.
///
/// A binary search over the file's line offsets: the rows are sorted numerically by app-id, which
/// is the property that makes this cheap and which a test pins against a linear scan.
///
/// **Offsets are stepped over bytes, not characters.** Titles are UTF-8 and plenty are not ASCII,
/// so slicing at a computed midpoint splits a character and panics; newlines are ASCII, so the
/// line boundaries this lands on are always character boundaries.
#[must_use]
pub fn by_id(app_id: u32) -> Option<Entry> {
    let bytes = SNAPSHOT.as_bytes();
    let (mut low, mut high) = (*DATA_START, bytes.len());
    while low < high {
        let middle = low + (high - low) / 2;
        let start = bytes[low..middle]
            .iter()
            .rposition(|byte| *byte == b'\n')
            .map_or(low, |at| low + at + 1);
        let end = bytes[start..]
            .iter()
            .position(|byte| *byte == b'\n')
            .map_or(bytes.len(), |at| start + at);
        let line = &SNAPSHOT[start..end];
        match leading_id(line) {
            Some(found) if found == app_id => return parse(line),
            // Backing up to the line start can land on the line we already rejected, so the step
            // forward is past its END. Without that this loops for ever on the low side.
            Some(found) if found < app_id => {
                if end >= high {
                    return None;
                }
                low = end + 1;
            }
            Some(_) => high = start,
            None => return None,
        }
    }
    None
}

/// Several games by app-id, aligned with the ids given so a caller can zip the two.
///
/// One binary search each rather than one scan: the file is sorted, so eighteen probes beat
/// 188,701 line starts for any batch smaller than about ten thousand.
#[must_use]
pub fn by_ids(app_ids: &[u32]) -> Vec<Option<Entry>> {
    app_ids.iter().map(|id| by_id(*id)).collect()
}

/// One game by title, compared loosely.
///
/// **Only the last field is looked at.** The title is the final column precisely so it can hold
/// anything but a tab, and a search that looked anywhere else would match a developer's name or a
/// number in the tag list.
///
/// Comparison is [`comparable`]: case is folded and everything that is not a letter or a digit is
/// dropped, so `"Half-Life 2"`, `"half life 2"` and `"HALF:LIFE2"` are one title. That is the
/// existing normaliser the curated table already matches with, not a second one invented here.
///
/// # Errors
///
/// [`NotOne`] when the title matches no game or several. **Several is common, not theoretical:**
/// measured over this snapshot, 3,343 of 184,386 distinct folded titles reach more than one
/// app-id — 1.8%, and "Escape" alone reaches thirteen ("Echo", "Nightshift" and "Hide and Seek"
/// eight each). An earlier note here
/// cited 4 in 2,282, which was measured over the 415-entry curated table and is not the rate over
/// a whole store.
///
/// A title that folds away to nothing — 25 rows: `?`, punctuation alone, or blank — never
/// matches, and neither does an empty needle. Otherwise every one of them would answer at once.
pub fn by_name(title: &str) -> Result<Entry, NotOne> {
    // **The strict form gets first refusal.** The relaxed one is consulted only where the exact
    // title matched nothing, so a store's plain wording can never be overridden by a shortened
    // one — and a relaxed form matching several is still refused, not guessed.
    let strict = rows_titled(&comparable(title));
    let chosen = match (strict, without_edition(title)) {
        ([], Some(plain)) => rows_titled(&comparable(&plain)),
        _ => strict,
    };
    match chosen {
        [] => Err(NotOne::Nothing),
        [one] => parse(one).ok_or(NotOne::Nothing),
        several => {
            let mut ids: Vec<u32> = several.iter().filter_map(|line| leading_id(line)).collect();
            ids.sort_unstable();
            Err(NotOne::Several(ids))
        }
    }
}

/// Several games by title, aligned with the titles given so a caller can zip the two.
///
/// One index lookup each. It exists, like [`by_ids`], so a caller holding a list of either kind
/// has one shape to use — not because the batch is cheaper than the loop, which it was while a
/// title cost a scan of the file.
#[must_use]
pub fn by_names(titles: &[&str]) -> Vec<Result<Entry, NotOne>> {
    titles.iter().map(|title| by_name(title)).collect()
}

/// Every data row whose title folds to something, sorted by that folded title: the index
/// [`by_name`] binary-searches.
///
/// Built on the first title lookup of the process, from one pass over the file, and holding one
/// pointer per row — 3 MB over 188,701 rows — rather than a copy of any title. Rows whose title
/// folds away to nothing (the `?` marker, punctuation alone) are left out, so they can never
/// answer: otherwise every one of them would answer to one another and to an empty needle.
static BY_TITLE: std::sync::LazyLock<Vec<&'static str>> = std::sync::LazyLock::new(|| {
    let mut sorted: Vec<&'static str> = rows()
        .filter(|line| !folded_title(line).is_empty())
        .collect();
    // The key allocates, so it is computed once per row here rather than once per comparison.
    sorted.sort_by_cached_key(|line| folded_title(line));
    sorted
});

/// A row's title, folded with [`comparable`]. The title is the last field: `rsplit` stops at the
/// first tab from the right, so this reads one field however many columns the format grows.
fn folded_title(line: &str) -> String {
    comparable(line.rsplit('\t').next().unwrap_or_default())
}

/// The rows titled exactly `folded`: the first by binary search, then every neighbour that
/// agrees. None for an empty needle, which is not a title.
fn rows_titled(folded: &str) -> &'static [&'static str] {
    if folded.is_empty() {
        return &[];
    }
    let sorted: &'static [&'static str] = &BY_TITLE;
    let start = sorted.partition_point(|line| folded_title(line).as_str() < folded);
    let end = start + sorted[start..].partition_point(|line| folded_title(line) == folded);
    &sorted[start..end]
}

/// Every data row, with the commented header skipped.
pub fn rows() -> impl Iterator<Item = &'static str> {
    SNAPSHOT
        .lines()
        .filter(|line| !line.starts_with('#') && !line.is_empty())
}

/// Every game in the snapshot, parsed.
pub fn entries() -> impl Iterator<Item = Entry> {
    rows().filter_map(parse)
}

/// The app-id a row starts with, without splitting the rest of it.
fn leading_id(line: &str) -> Option<u32> {
    line.split('\t').next()?.parse().ok()
}

/// A row into an [`Entry`], or `None` if it is not one — a comment, the wrong width, or an
/// app-id that is not a number.
///
/// **Every other cell reads as what it says, or as unknown.** A cell that is neither a value its
/// column holds nor [`UNKNOWN`] reads as unknown too, rather than costing the whole row: the
/// app's id and what else is known still serve every lookup. Such a cell is a fault in the file,
/// and [`super::doctor`] is what reports it — over the same grammar, [`check_cell`].
fn parse(line: &'static str) -> Option<Entry> {
    let field: Vec<&'static str> = line.split('\t').collect();
    if field.len() != COLUMNS.len() {
        return None;
    }
    let app_id = field[APP_ID].parse().ok()?;
    let name = if field[NAME] == UNKNOWN {
        ""
    } else {
        field[NAME]
    };
    if field[KIND..NAME].iter().all(|cell| *cell == UNKNOWN) {
        return Some(Entry {
            app_id,
            name,
            details: None,
        });
    }
    let known = |at: usize| (field[at] != UNKNOWN).then_some(field[at]);
    let languages = [field[LANG_UI], field[LANG_UI + 1], field[LANG_UI + 2]];
    Some(Entry {
        app_id,
        name,
        details: Some(Details {
            kind: known(KIND).and_then(|cell| number(cell).ok()),
            band: known(BAND).and_then(|cell| band(cell).ok()),
            approval: known(APPROVAL).and_then(|cell| percent(cell).ok()),
            reviews: known(REVIEWS).and_then(|cell| number(cell).ok()),
            released: Release::from_cell(field[RELEASED]).ok().flatten(),
            os: known(OS).and_then(|cell| os(cell).ok()),
            vr: known(VR).and_then(|cell| flag(cell).ok()),
            early_access: known(EARLY).and_then(|cell| flag(cell).ok()),
            deck: known(DECK).and_then(|cell| deck(cell).ok()),
            compat: known(COMPAT).and_then(|cell| compat(cell).ok()),
            languages: (!languages.contains(&UNKNOWN))
                .then(|| Languages::from_columns(languages).ok())
                .flatten(),
            tagids: known(TAGIDS).filter(|cell| id_list(cell).is_ok()),
            included: known(INCL).filter(|cell| id_list(cell).is_ok()),
            feats: known(FEATS).filter(|cell| id_list(cell).is_ok()),
            developers: known(DEVS),
            publishers: known(PUBS),
        }),
    })
}

/// Whether `cell` is something column `column` can hold: a value of its kind, or [`UNKNOWN`] in
/// any column but the app-id's.
///
/// # Errors
///
/// What is wrong with it, in words.
pub(crate) fn check_cell(column: usize, cell: &str) -> Result<(), String> {
    if cell == UNKNOWN && column != APP_ID {
        return Ok(());
    }
    match column {
        APP_ID | KIND | REVIEWS => number(cell).map(drop),
        BAND => band(cell).map(drop),
        APPROVAL => percent(cell).map(drop),
        RELEASED => Release::from_cell(cell).map(drop),
        OS => os(cell).map(drop),
        VR | EARLY => flag(cell).map(drop),
        DECK => deck(cell).map(drop),
        COMPAT => compat(cell).map(drop),
        at if (LANG_UI..LANG_UI + 3).contains(&at) => from_base36_wide(cell)
            .map(drop)
            .map_err(|why| format!("{cell:?}: {why}")),
        TAGIDS | INCL | FEATS => id_list(cell),
        DEVS | PUBS | NAME => Ok(()),
        _ => Err(format!("there is no column {column}")),
    }
}

fn number(cell: &str) -> Result<u32, String> {
    cell.parse()
        .map_err(|_| format!("{cell:?} is not a number"))
}

/// A band digit: Valve's own `review_score`, 0-9.
fn band(cell: &str) -> Result<Rating, String> {
    u8::try_from(number(cell)?)
        .ok()
        .and_then(Rating::from_valve_score)
        .ok_or_else(|| format!("{cell:?} is not a band, 0-9"))
}

fn percent(cell: &str) -> Result<u32, String> {
    number(cell).and_then(|value| match value {
        0..=100 => Ok(value),
        _ => Err(format!("{cell:?} is not a percentage")),
    })
}

/// The 1/2/4 bit mask of Windows, macOS and Linux.
fn os(cell: &str) -> Result<Os, String> {
    number(cell).and_then(|bits| match bits {
        0..=7 => Ok(Os {
            windows: bits & 1 != 0,
            mac: bits & 2 != 0,
            linux: bits & 4 != 0,
        }),
        _ => Err(format!("{cell:?} is not an os mask, 0-7")),
    })
}

fn flag(cell: &str) -> Result<bool, String> {
    match cell {
        "1" => Ok(true),
        "0" => Ok(false),
        _ => Err(format!("{cell:?} is not 0 or 1")),
    }
}

/// Valve's Deck category, 0-3.
fn deck(cell: &str) -> Result<u32, String> {
    number(cell).and_then(|value| match value {
        0..=3 => Ok(value),
        _ => Err(format!("{cell:?} is not a Deck category, 0-3")),
    })
}

fn compat(cell: &str) -> Result<Compat, String> {
    let mut chars = cell.chars();
    match (chars.next(), chars.next()) {
        (Some(digit), None) => Compat::from_digit(digit).map_err(|why| format!("{cell:?}: {why}")),
        _ => Err(format!("{cell:?} is not one compat digit")),
    }
}

/// A comma-separated list of base-36 ids — empty when the store lists none.
fn id_list(cell: &str) -> Result<(), String> {
    cell.split(',')
        .filter(|token| !token.is_empty())
        .try_for_each(|token| {
            from_base36(token)
                .map(drop)
                .map_err(|why| format!("{token:?}: {why}"))
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The index constants against the shared column list. This is the drift guard: the writer
    /// builds its header from `COLUMNS` and the reader indexes by these, so a column inserted in
    /// the middle has to fail here rather than silently shift every field by one.
    #[test]
    fn the_column_indices_name_the_columns_they_index() {
        for (at, expected) in [
            (APP_ID, "app_id"),
            (KIND, "type"),
            (BAND, "band"),
            (APPROVAL, "approval"),
            (REVIEWS, "reviews"),
            (RELEASED, "released"),
            (OS, "os"),
            (VR, "vr"),
            (EARLY, "early"),
            (DECK, "deck"),
            (COMPAT, "compat"),
            (LANG_UI, "lang_ui"),
            (TAGIDS, "tagids(base36)"),
            (INCL, "incl(base36)"),
            (FEATS, "feats(base36)"),
            (DEVS, "devs"),
            (PUBS, "pubs"),
            (NAME, "name"),
        ] {
            assert_eq!(COLUMNS[at], expected, "column {at}");
        }
        assert_eq!(
            NAME,
            COLUMNS.len() - 1,
            "the title must stay the last field"
        );
        assert_eq!(COLUMNS[LANG_UI + 1], "lang_audio");
        assert_eq!(COLUMNS[LANG_UI + 2], "lang_subs");
    }

    /// The compiled-in file must be the one this module was written against.
    #[test]
    fn the_snapshot_header_matches_the_shared_column_list() {
        let first = SNAPSHOT.lines().next().expect("a header line");
        let named: Vec<&str> = first.trim_start_matches("# ").split('\t').collect();
        assert_eq!(named, COLUMNS, "the compiled-in file has a different shape");
    }

    #[test]
    fn a_known_game_is_found_by_its_app_id() {
        let portal = by_id(620).expect("Portal 2 is in the snapshot");
        assert_eq!(portal.name, "Portal 2");
        let details = portal.details.expect("Portal 2 is described");
        assert_eq!(details.band, Some(Rating::OverwhelminglyPositive));
        assert_eq!(details.released, Some(Release::Out("2011-04-19")));
        let os = details.os.expect("its systems are known");
        assert!(os.windows && os.linux);
        assert_eq!(details.early_access, Some(false));
        let languages = details.languages.expect("its languages are known");
        assert_eq!(languages.supported.count_ones(), 27, "27 listed languages");
        assert_eq!(languages.full_audio.count_ones(), 5, "5 dubbed");
    }

    /// The binary search, against the answer a plain scan gives, over both ends and the middle.
    /// A hand-written search is exactly the thing that works for every id but the boundaries.
    #[test]
    fn the_binary_search_agrees_with_a_scan() {
        let all: Vec<u32> = rows().filter_map(leading_id).collect();
        assert!(
            all.len() > 1000,
            "the snapshot looks truncated: {} rows",
            all.len()
        );
        let probes: Vec<u32> = [
            all[0],
            all[1],
            all[all.len() / 2],
            all[all.len() - 2],
            all[all.len() - 1],
        ]
        .into_iter()
        .chain(all.iter().step_by(all.len() / 97).copied())
        .collect();
        for id in probes {
            let found =
                by_id(id).unwrap_or_else(|| panic!("app {id} is in the file but was not found"));
            assert_eq!(found.app_id, id);
        }
    }

    /// The index, against the answer a plain scan gives, for titles from both ends of the file,
    /// the middle and a hundred between — every row of each title, since a search that finds the
    /// first of a run of equal keys and not the rest is exactly the boundary a hand-written one
    /// gets wrong. One scan builds the oracle for all the probes; a scan per probe would take
    /// minutes in a debug build.
    #[test]
    fn the_title_index_agrees_with_a_scan() {
        let mut scanned: std::collections::HashMap<String, Vec<u32>> =
            std::collections::HashMap::new();
        for line in rows() {
            let folded = folded_title(line);
            if !folded.is_empty() {
                scanned.entry(folded).or_default().extend(leading_id(line));
            }
        }
        let all: Vec<&str> = rows().collect();
        let probes = [
            all[0],
            all[1],
            all[all.len() / 2],
            all[all.len() - 2],
            all[all.len() - 1],
        ]
        .into_iter()
        .chain(all.iter().step_by(all.len() / 97).copied());
        for line in probes {
            let folded = folded_title(line);
            let mut found: Vec<u32> = rows_titled(&folded)
                .iter()
                .filter_map(|row| leading_id(row))
                .collect();
            found.sort_unstable();
            let mut expected = scanned.get(&folded).cloned().unwrap_or_default();
            expected.sort_unstable();
            assert_eq!(found, expected, "{folded:?}");
        }
    }

    #[test]
    fn an_app_id_the_snapshot_does_not_hold_is_not_invented() {
        for absent in [0, 1, 9, 11, u32::MAX, 4_294_967_294] {
            if rows().filter_map(leading_id).any(|id| id == absent) {
                continue;
            }
            assert_eq!(by_id(absent), None, "app {absent} should not resolve");
        }
    }

    #[test]
    fn several_app_ids_come_back_aligned_with_the_ids_asked_for() {
        let answers = by_ids(&[620, 1, 440, 4_294_967_295]);
        assert_eq!(answers.len(), 4, "one answer per id, in order");
        assert_eq!(answers[0].expect("620").app_id, 620);
        assert_eq!(answers[1], None, "app 1 is not in the snapshot");
        assert_eq!(answers[2].expect("440").app_id, 440);
        assert_eq!(answers[3], None);
    }

    /// Case and punctuation are the two things the loose match is for.
    #[test]
    fn a_title_matches_loosely() {
        let canonical = by_name("Portal 2").expect("Portal 2 resolves");
        for spelling in [
            "portal 2",
            "PORTAL 2",
            "Portal2",
            "  Portal: 2  ",
            "p-o-r-t-a-l 2",
        ] {
            let found = by_name(spelling).unwrap_or_else(|why| panic!("{spelling:?}: {why}"));
            assert_eq!(found.app_id, canonical.app_id, "{spelling:?}");
        }
    }

    /// The fallback resolves an edition-suffixed title, and only where the strict form failed.
    ///
    /// The wordings are real: these are titles a Fanatical capture printed that Steam holds under
    /// a plainer name.
    #[test]
    fn edition_wording_is_stripped_only_as_a_fallback() {
        for (printed, expected) in [
            ("Deathloop - Deluxe Edition", "DEATHLOOP"),
            ("Metro Exodus - Gold Edition", "Metro Exodus"),
            ("Coromon Deluxe Edition", "Coromon"),
            ("Redout 2 - Ultimate Edition", "Redout 2"),
        ] {
            let found = by_name(printed).unwrap_or_else(|why| panic!("{printed:?}: {why}"));
            assert_eq!(found.name, expected, "{printed:?}");
        }
    }

    /// The strict form wins where both would match, so a store's plain wording is never
    /// overridden by a shortened one.
    #[test]
    fn the_strict_form_is_preferred_over_the_stripped_one() {
        let direct = by_name("Portal 2").expect("Portal 2 exists under its own name");
        assert_eq!(
            direct.app_id, 620,
            "asking for it must not reach the fallback"
        );
    }

    /// Stripping must not turn one answer into several unnoticed.
    #[test]
    fn a_stripped_title_matching_several_is_still_refused() {
        assert!(
            matches!(by_name("Deadlink"), Err(NotOne::Several(_))),
            "two games share this title; the lookup must refuse"
        );
        assert!(
            matches!(
                by_name("Deadlink - Deluxe Edition"),
                Err(NotOne::Several(_))
            ),
            "and the stripped form must refuse for the same reason"
        );
    }

    /// Nothing to strip means no second lookup is attempted at all.
    #[test]
    fn a_plain_title_has_no_second_form() {
        assert_eq!(without_edition("Portal 2"), None);
        assert_eq!(
            without_edition("Deathloop - Deluxe Edition").as_deref(),
            Some("deathloop")
        );
        assert_eq!(
            without_edition("Metro Exodus - Gold Edition").as_deref(),
            Some("metro exodus")
        );
        assert_eq!(
            without_edition("Complete"),
            None,
            "a bare edition word is a title"
        );
        assert_eq!(without_edition("Deluxe"), None);
    }

    #[test]
    fn a_title_nothing_carries_is_an_error_rather_than_a_guess() {
        assert_eq!(
            by_name("a game that does not exist anywhere at all"),
            Err(NotOne::Nothing)
        );
        assert_eq!(
            by_name(""),
            Err(NotOne::Nothing),
            "an empty needle matches nothing"
        );
        assert_eq!(
            by_name("???"),
            Err(NotOne::Nothing),
            "so does one that folds away"
        );
    }

    /// Ambiguity is reported, never resolved by picking one. Measured over this snapshot, 3,343
    /// folded titles reach more than one app-id.
    #[test]
    fn a_title_several_games_share_is_an_error_naming_them() {
        let Err(NotOne::Several(ids)) = by_name("Echo") else {
            panic!("several games are called Echo; the lookup should refuse to choose");
        };
        assert!(ids.len() > 1, "at least two");
        assert!(
            ids.windows(2).all(|pair| pair[0] < pair[1]),
            "ascending and distinct"
        );
        for id in &ids {
            let found =
                by_id(*id).unwrap_or_else(|| panic!("app {id} was named but does not resolve"));
            assert_eq!(comparable(found.name), "echo");
        }
    }

    /// The search must read the last field and nothing else — a developer's name, a publisher's,
    /// or a number that happens to appear in a tag list must never answer a title query.
    #[test]
    fn only_the_last_field_is_searched() {
        // "Valve" is a developer on many rows. Whatever it resolves to, it must be a GAME titled
        // Valve, never one of Valve's games matched through the `devs` column.
        match by_name("Valve") {
            Ok(found) => assert_eq!(
                comparable(found.name),
                "valve",
                "matched something not titled Valve"
            ),
            Err(NotOne::Several(ids)) => {
                for id in ids {
                    let found = by_id(id).expect("named app resolves");
                    assert_eq!(comparable(found.name), "valve");
                }
            }
            Err(NotOne::Nothing) => {}
        }
        // A base-36 tag list token, which appears in the middle of thousands of rows.
        assert_eq!(
            by_name("1a7"),
            Err(NotOne::Nothing),
            "a tag token is not a title"
        );
    }

    #[test]
    fn several_titles_come_back_aligned_with_the_titles_asked_for() {
        let answers = by_names(&["Portal 2", "no such game whatsoever", "Team Fortress 2"]);
        assert_eq!(answers.len(), 3);
        assert_eq!(answers[0].as_ref().expect("Portal 2").app_id, 620);
        assert_eq!(answers[1], Err(NotOne::Nothing));
        assert_eq!(answers[2].as_ref().expect("TF2").app_id, 440);
    }

    /// The batch must give the same answers as the single form, or it is a second implementation.
    #[test]
    fn the_batch_agrees_with_the_single_lookup() {
        let titles = [
            "Portal 2",
            "Half-Life",
            "Echo",
            "nothing here",
            "Team Fortress 2",
            "",
        ];
        let batched = by_names(&titles);
        for (title, batch) in titles.iter().zip(batched) {
            assert_eq!(by_name(title), batch, "{title:?}");
        }
        let ids = [10, 620, 440, 7, 5_285_050];
        assert_eq!(
            by_ids(&ids),
            ids.iter().map(|id| by_id(*id)).collect::<Vec<_>>()
        );
    }

    /// An app the file knows nothing about but its id still resolves, carrying what is known.
    #[test]
    fn an_app_known_only_by_its_id_resolves_to_its_id_and_nothing_more() {
        let undescribed: Vec<Entry> = entries().filter(|e| e.details.is_none()).collect();
        assert!(!undescribed.is_empty(), "the snapshot records some");
        for entry in &undescribed {
            assert!(entry.app_id > 0);
            assert_eq!(entry.name, "", "the file's `?` marker is not a title");
            assert_eq!(
                by_id(entry.app_id),
                Some(*entry),
                "it is still findable by id"
            );
        }
    }

    /// The id columns resolve through the generated models — the join the snapshot exists for.
    #[test]
    fn the_id_columns_resolve_through_the_generated_models() {
        let portal = by_id(620).expect("Portal 2").details.expect("described");

        let tags: Vec<&str> = portal
            .tag_ids()
            .expect("known")
            .filter_map(super::super::tags::name)
            .collect();
        assert!(
            tags.len() >= 15,
            "Portal 2 carries a full tag list, got {tags:?}"
        );
        assert!(tags.contains(&"Puzzle"), "expected Puzzle among {tags:?}");

        let feats: Vec<&str> = portal
            .feature_ids()
            .expect("known")
            .filter_map(super::super::categories::name)
            .collect();
        assert!(
            feats.contains(&"Single-player"),
            "expected Single-player among {feats:?}"
        );
        assert!(
            feats.contains(&"Steam Achievements"),
            "expected achievements among {feats:?}"
        );

        assert_eq!(
            portal.developers().expect("known").collect::<Vec<_>>(),
            ["Valve"]
        );
        assert_eq!(
            portal.publishers().expect("known").collect::<Vec<_>>(),
            ["Valve"]
        );
        assert_eq!(
            portal.included_apps().map(Iterator::count),
            Some(0),
            "Portal 2 names no sibling app, which is known, not unknown"
        );
    }

    /// EVERY row parses. `entries()` skips what it cannot read, so without this a band digit
    /// Valve widened, a column added to the writer alone, or any other shape change would show up
    /// as games quietly missing from every lookup rather than as a failure.
    ///
    /// This replaces a test that checked a generated band sidecar named all ten digits. The
    /// sidecar is gone — `Rating` was always the real model — and the property that mattered is
    /// stronger stated this way: the band is one of the things a row needs in order to parse.
    #[test]
    fn no_row_is_silently_unreadable() {
        let rows = rows().count();
        let parsed = entries().count();
        assert_eq!(
            parsed,
            rows,
            "{} of {rows} rows did not parse",
            rows - parsed
        );
        assert!(rows > 100_000, "the snapshot looks truncated: {rows} rows");

        // And the band column really is being read, not defaulted past.
        let mut bands: Vec<Rating> = Vec::new();
        for entry in entries() {
            if let Some(band) = entry.details.and_then(|details| details.band)
                && !bands.contains(&band)
            {
                bands.push(band);
            }
        }
        assert!(
            bands.len() >= 5,
            "only {} distinct bands across the catalogue",
            bands.len()
        );
        assert!(
            bands.contains(&Rating::TooFewReviews),
            "band 0 must read as Steam declining"
        );
        assert!(
            bands.contains(&Rating::OverwhelminglyPositive),
            "band 9 must read as the top"
        );
    }

    /// Every tag and feature id in the whole file resolves, or the models are out of date with
    /// the snapshot beside them.
    #[test]
    fn every_id_in_the_snapshot_is_one_the_models_can_name() {
        let (mut tags, mut feats, mut unknown_tags, mut unknown_feats) = (0, 0, 0, 0);
        for entry in entries() {
            let Some(details) = entry.details else {
                continue;
            };
            for id in details.tag_ids().into_iter().flatten() {
                tags += 1;
                if super::super::tags::name(id).is_none() {
                    unknown_tags += 1;
                }
            }
            for id in details.feature_ids().into_iter().flatten() {
                feats += 1;
                if super::super::categories::of(id).is_none() {
                    unknown_feats += 1;
                }
            }
        }
        assert!(
            tags > 100_000 && feats > 100_000,
            "counted {tags} tags, {feats} features"
        );
        assert_eq!(
            unknown_tags, 0,
            "{unknown_tags} of {tags} tag ids have no name"
        );
        assert_eq!(
            unknown_feats, 0,
            "{unknown_feats} of {feats} feature ids have no name"
        );
    }

    /// Every shape the released column holds reads back as itself, and anything else is refused
    /// with the shapes it could have been.
    #[test]
    fn the_released_column_reads_every_shape_it_can_hold() {
        for (cell, read) in [
            ("2011-04-19", Some(Release::Out("2011-04-19"))),
            ("~2026-11-15", Some(Release::Planned("2026-11-15"))),
            (UNANNOUNCED, Some(Release::Unannounced)),
            (UNDATED, Some(Release::Undated)),
            (UNKNOWN, None),
        ] {
            assert_eq!(Release::from_cell(cell), Ok(read), "{cell:?}");
            if let Some(release) = read {
                assert_eq!(release.cell(), cell, "{release:?} is written as it is read");
            }
        }
        assert!(Release::Planned("2026-11-15").coming_soon() && Release::Unannounced.coming_soon());
        assert!(!Release::Out("2011-04-19").coming_soon() && !Release::Undated.coming_soon());
        assert_eq!(Release::Planned("2026-11-15").date(), Some("2026-11-15"));
        assert_eq!(Release::Undated.date(), None);
        for junk in ["", "soon", "2011-4-19", "2011-04", "~TBA", "~", "tba", "x"] {
            let err = Release::from_cell(junk).expect_err(junk);
            assert!(err.contains(UNANNOUNCED), "{junk:?}: {err}");
        }
    }

    /// A row that knows some cells and not others — what a delisted app with a few facts looks
    /// like — reads what it knows and leaves the rest unknown, rather than being dropped.
    #[test]
    fn a_partly_known_row_reads_what_it_knows_and_nothing_else() {
        const ROW: &str = "5009660\t0\t?\t?\t?\tTBA\t1\t?\t?\t?\t?\ty9\t5c\t0\t2ya,3ga\t?\t?\tOuroboros Play Ltd.\t\tHaunted Love";
        let entry = parse(ROW).expect("a whole row");
        assert_eq!((entry.app_id, entry.name), (5_009_660, "Haunted Love"));
        let details = entry.details.expect("something is known");
        assert_eq!(details.kind, Some(0));
        assert_eq!(
            (details.band, details.approval, details.reviews),
            (None, None, None)
        );
        assert_eq!(details.released, Some(Release::Unannounced));
        assert_eq!(
            details.os,
            Some(Os {
                windows: true,
                mac: false,
                linux: false
            })
        );
        assert_eq!(
            (
                details.vr,
                details.early_access,
                details.deck,
                details.compat
            ),
            (None, None, None, None)
        );
        let languages = details.languages.expect("known");
        assert_eq!(
            (
                languages.supported,
                languages.full_audio,
                languages.subtitles
            ),
            (1233, 192, 0)
        );
        assert_eq!(
            details.tag_ids().map(Iterator::collect::<Vec<u32>>),
            Some(vec![3_826, 4_474])
        );
        assert!(details.included_apps().is_none() && details.feature_ids().is_none());
        assert_eq!(
            details.developers().map(Iterator::collect::<Vec<_>>),
            Some(vec!["Ouroboros Play Ltd."])
        );
        assert_eq!(
            details.publishers().map(Iterator::count),
            Some(0),
            "an empty cell is a store listing none, not unknown"
        );
    }

    /// A cell that is neither a value nor `?` costs that cell, not the row — and the grammar the
    /// doctor checks the file with says what is wrong with it.
    #[test]
    fn a_cell_that_is_no_value_of_its_column_reads_as_unknown_and_is_named_by_the_grammar() {
        const ROW: &str =
            "620\t0\tx\t101\t5\t2011-4-19\t9\t2\t0\t4\t!!\t1\t0\t?\tzz\t\t\tValve\tValve\tPortal 2";
        let details = parse(ROW).expect("a whole row").details.expect("known");
        assert_eq!((details.kind, details.reviews), (Some(0), Some(5)));
        assert_eq!(
            (details.band, details.approval, details.released),
            (None, None, None)
        );
        assert_eq!(
            (details.os, details.vr, details.deck, details.compat),
            (None, None, None, None)
        );
        assert_eq!(
            details.languages, None,
            "one unknown mask makes the three unknown"
        );
        assert_eq!(details.tag_ids().map(Iterator::count), Some(1));
        for (column, cell) in [
            (BAND, "x"),
            (APPROVAL, "101"),
            (RELEASED, "2011-4-19"),
            (OS, "9"),
            (VR, "2"),
            (DECK, "4"),
            (COMPAT, "!!"),
        ] {
            assert!(
                check_cell(column, cell).is_err(),
                "{} {cell:?}",
                COLUMNS[column]
            );
        }
        for (column, cell) in [
            (KIND, "?"),
            (NAME, "?"),
            (DEVS, ""),
            (TAGIDS, ""),
            (LANG_UI, "0"),
        ] {
            assert_eq!(
                check_cell(column, cell),
                Ok(()),
                "{} {cell:?}",
                COLUMNS[column]
            );
        }
        assert!(
            check_cell(APP_ID, UNKNOWN).is_err(),
            "the app-id is never unknown"
        );
    }
}
